### ISSUE TITLE
Serialization with FOSUser

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasApiBundle#110]
I'm using the FOSUserBundle with my `User` entity. I wish to hide some properties of the `User` entity, for example the `password` and the `plainPassword`. However, I still need to be able to use the `plainPassword` property in the `PUT` or `POST` to set or update the password of the user.

Here's the configuration:

```
<?php
// src/AppBundle/Entity/User.php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Entity\User as FosUser;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * User.
 *
 * @ORM\Entity
 */
class User extends FosUser
{
    /**
     * @var int
     *
     * @ORM\Column(type = "integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy = "AUTO")
     * @Groups({"user"})
     */
    protected $id;

    /**
     * @var string
     *
     * @Groups({"user"})
     */
    protected $email;

    /**
     * @var string
     *
     * @ORM\Column(type = "string", length = 45)
     * @Groups({"user"})
     */
    private $username;

    /**
     * @var string
     *
     * @Groups({"password"})
     */
    protected $plainPassword;

    public function __construct()
    {
        parent::__construct();
    }
}
```

```yaml
# app/config/services.yml
resource.user:
    parent:    api.resource
    arguments: [ AppBundle\Entity\User ]
    calls:
        -      [ initNormalizationContext, [ { groups: [ user ] } ] ]
        -      [ initDenormalizationContext, [ { groups: [ password, user ] } ] ]
    tags:      [ { name: api.resource } ]
```

When I `GET` an entity or a collection, the properties are hidden as expected. However the `POST` fails stating the column `password` cannot be null.

Have you any idea on what may be the problem?
