### ISSUE TITLE
Example for custom POST

### ISSUE THREAD

**Issue by felicitus** [dunglas/DunglasApiBundle#149]
The documentation doesn't list an example for a custom POST operation. I tried a few things and my custom POST action is being called, however, when I attempt to serialize the newly created entity, I receive "The current request doesn't have an associated resource.". I copied some code from the cpost () method.

My configuration looks like this:

```yaml
    resource.tempimage.collection_operation.custom_post:
            class:     "Dunglas\ApiBundle\Api\Operation\Operation"
            public:    false
            factory:   [ "@api.operation_factory", "createCollectionOperation" ]
            arguments:
                 -    "@resource.tempimage"               # Resource
                 -    [ "POST" ]                 # Methods
                 -    "/temporaryImage/upload"           # Path
                 -    "PartKeeprImageBundle:TemporaryImage:upload"         # Controller
                 -    "TemporaryImageUpload"                 # Route name
                 -    # Context (will be present in Hydra documentation)
                      "@type":       "hydra:Operation"
                      "hydra:title": "A custom operation"
                      "returns":     "xmls:string"

    resource.tempimage:
        parent:    "api.resource"
        arguments: [ "PartKeepr\\ImageBundle\\Entity\\TempImage" ]
        tags:      [ { name: "api.resource" } ]
        calls:
            -       method:     "initCollectionOperations"
                    arguments: [ [ "@resource.tempimage.collection_operation.custom_post" ] ]
```

Inside my controller, I try to get the resource, which results in the exception `The current request doesn't have an associated resource.`:

```php
class TemporaryImageController extends ResourceController {
/**
     * Handles a temporary image upload
     *
     * @Route("/api/temporaryImage/upload", defaults={"method" = "get","_format" = "json"})
     * @RequestParam(name="url",description="An URL where the image is located")
     * ApiDoc(section="image",output="PartKeepr\ImageBundle\Response\TemporaryImageUploadResponse")
     * @View()
     */
    public function uploadAction (Request $request) {
        $resource = $this->getResource($request);
    }
}
*/
