### ISSUE TITLE
The class AppBundle\Entity roduct does not exist in . (which is being imported from

### ISSUE THREAD

**Issue by emillosanti** [dunglas/DunglasApiBundle#162]
following installation steps : 
https://github.com/dunglas/DunglasApiBundle/blob/master/Resources/doc/getting-started.md#registering-the-services

error:
The class AppBundle\Entityroduct does not exist in . (which is being imported from ".../routing.yml").

replacing entity with : MyProduct works ( and replacing affected service declaration ).

edit:
in addition, declaring a class AppBundle\Entity\Potential produces the same error:
The class AppBundle\Entityotential does not exist in . (which is being imported from ".../routing.yml").

**Comment by theofidry** [comment]
Could you past your service declaration?

**Comment by emillosanti** [comment]
services:
    resource.product:
        parent:    "api.resource"
        arguments: [ "AppBundle\Entity\Product" ]
        tags:      [ { name: "api.resource" } ]

**Comment by theofidry** [comment]
try: 

```yaml
services:
    resource.product:
    parent: "api.resource"
    arguments: [ "AppBundle\\Entity\\Product" ]
    tags: [ { name: "api.resource" } ]
```

**Comment by dunglas** [comment]
I think we should update the documentation to use `\\` everywhere to avoid that kind of mistake.

**Comment by emillosanti** [comment]
thanks, it works.

**Comment by theofidry** [comment]
Is that really it? It's more like a bug. We didn't have this problem on previous versions and whenever your defining the value of `class` for a service declaration I don't remember having to do that.

**Comment by dunglas** [comment]
It was exactly the same, it's how YAML works (another argument for XML services definition ;-)). The first version of the doc was using `\\` everywhere for that reason but it has been changed to look better. Maybe that it was not a good idea.

**Comment by theofidry** [comment]
The following definitely works for us:

```yaml
    resource.content:
        parent:       api.resource
        arguments:    [ AppBundle\Entity\Content ]
```
