### ISSUE TITLE
"No resource found for object of type ..." for resources with subclass

### ISSUE THREAD

**Issue by teohhanhui** [dunglas/DunglasApiBundle#184]
Given

```php
// src/AppBundle/Entity/Book.php
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Dunglas\ApiBundle\Annotation\Iri;

/**
 * @ORM\Entity
 * @Iri("http://schema.org/Book")
 */
class Book extends CreativeWork
{
    ...
}
```

```php
// src/AppBundle/Entity/CreativeWork.php
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Dunglas\ApiBundle\Annotation\Iri;

/**
 * @ORM\Entity
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"creative_work" = "CreativeWork", "book" = "Book"})
 * @Iri("http://schema.org/CreativeWork")
 */
class CreativeWork extends Thing
{
    ...
}
```

```yaml
# app/config/services.yml
services:
    resource.book:
            parent: api.resource
            arguments:
                - AppBundle\Entity\Book
            tags:
                - name: api.resource

    resource.creative_work:
            parent: api.resource
            arguments:
                - AppBundle\Entity\CreativeWork
            tags:
                - name: api.resource
```

When accessing `/creative_works` the error `No resource found for object of type "AppBundle\Entity\Book"` is thrown.
