### ISSUE TITLE
A circular reference has been detected

### ISSUE THREAD

**Issue by felicitus** [dunglas/DunglasApiBundle#200]
Hi,

I just upgraded to the latest DunglasApiBundle. However, now my tree which previously serialized just fine, now throws an error:

```
{
@context: "/~felicitus/PartKeepr/web/app_dev.php/api/contexts/Error",
@type: "Error",
hydra:title: "An error occurred",
hydra:description: "A circular reference has been detected (configured limit: 1).",
trace: [
{
file: "/home/felicitus/public_html/PartKeepr/vendor/symfony/symfony/src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php",
line: 57,
function: "handleCircularReference",
class: "Symfony\Component\Serializer\Normalizer\AbstractNormalizer",
type: "->",
args: [
{
expanded: true
}
]
},
{
```

Any idea what could have caused this? The commit can be found here:
https://github.com/partkeepr/PartKeepr/commit/6b9b405a7a6dd15b04fc851c25b9da32918b2b14

**Comment by dunglas** [comment]
Did you upgrade from beta 2 or 3? Can your try to upgrade the circular reference limit? http://symfony.com/doc/current/components/serializer.html#handling-circular-references

Btw be careful the current upgrade, I'll introduce a lot of other BC break when I'll be back from vacation (3 weeks).

**Comment by felicitus** [comment]
I have no idea how to configure the circular reference limit. The documentation tells me to invoke a method, but I'm not instanciating the serializer manually, so I'm a bit lost there.

I'm not sure from which version I've upgraded, as I'm using dev-master. I think I'll postpone the update for now. Have a nice holiday! I'll be in holiday next week as well :)

**Comment by dunglas** [comment]
Currently you need to set the method in your bundle extension. Adding a configuration parameter for this option (in Symfony) can be interesting.

**Comment by dunglas** [comment]
And enjoy your holidays!

**Comment by felicitus** [comment]
You too! You aren't going to [CCCamp15](https://events.ccc.de/camp/2015/wiki/Main_Page) aren't you? ;)

**Comment by dunglas** [comment]
No I'll be far from Germany :)

**Comment by felicitus** [comment]
Sorry to bug you again, I still couldn't figure out how to increase the circular reference limit.

I tried to setup a new normalizer service:

```
    serializer.normalizer.custom:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        arguments:
            - "@serializer.mapping.class_metadata_factory"
            - null
            - "@serializer.property_accessor"
        tags:
            - { name: serializer.normalizer, priority: -1 }
        calls:
            - method: "setCircularReferenceLimit"
              arguments: [ [ 999 ] ]
```

By using that configuration, the request stalls and probably runs into a timeout.

Is there any way to implement the behavior of pre-beta2? I'm normalizing a tree structure, and as long as the @Depth annotation is not in place, I can't see if #259 is still working with 1.0 or dev-master :(
