### ISSUE TITLE
Read-only fields

### ISSUE THREAD

**Issue by lucascherifi** [dunglas/DunglasApiBundle#231]
One of my entities have a "dateCreated" field. I dont want this field to be writable because the value will be auto-generated after post. How to make this field "read-only" ?

**Comment by dunglas** [comment]
Add a getter but no setter.

**Comment by theofidry** [comment]
You have to you [Serialization groups](https://github.com/dunglas/DunglasApiBundle/blob/master/Resources/doc/serialization-groups-and-relations.md) for that to init the normalization/denormalization contexts, see [this example](https://github.com/dunglas/DunglasApiBundle).

**Comment by lucascherifi** [comment]
Thanks for these answers @dunglas and @theofidry and that a lot for this nice work.

@dunglas, I already tried that solution, but if I want to update a field not via an HTTP call but via an internal service in SF, I'll have to add a setter to be able to update this field "mannually" and so my field will be accessible for writable operations, what I dont want.

@theofidry : can you precise the link ?

**Comment by theofidry** [comment]
Sorry I can't check the link right now so I'm not sure I've given the good one. Anyway take a look at the example given with the FOSUserBundle.

**Comment by ogizanagi** [comment]
Actually, you'll only need to have the serialization group used for serialization on your date field (but not the one for deserialization). Then, it would be read-only:

```php
<?php

// src/AppBundle/Entity/Product.php

namespace AppBundle\Entity;

use Symfony\Component\Serializer\Annotation\Groups;

class Product
{
    // ...

    /**
     * ...
     * @Groups({"read", "write"})
     */
    public $name;

    /**
     * ...
     * @Groups({"read"})
     */
    public $createdAt;
}
```
```yaml
services:
    # ...

    resource.product:
        parent:    "api.resource"
        arguments: [ "AppBundle\Entity\Product" ]
        calls:
            -      method:    "initNormalizationContext"
                   arguments: [ { groups: [ "read" ] } ]
            -      method:    "initDenormalizationContext"
                   arguments: [ { groups: [ "write" ] } ]
        tags:      [ { name: "api.resource" } ]
```
