### ISSUE TITLE
could not cascade persist with one to many

### ISSUE THREAD

**Issue by emillosanti** [dunglas/DunglasApiBundle#232]
symfony 2.7.3
dunglas/api-bundle dev-master 1974ef6

```
/**
 * @ORM\Entity
 */
class Post {
//...
    /**
     * @ORM\OneToMany(targetEntity="Comment", mappedBy="post", cascade={"persist", "merge"})
     **/
    public $comments;
```

```
/**
 * @ORM\Entity
 */
class Comment {
//...
    /**
     * @ORM\ManyToOne(targetEntity="Post", inversedBy="comments")
     * @ORM\JoinColumn(name="post_id", referencedColumnName="id")
     **/
    public $post;

```

**services:**
```
    resource.post:
        parent: "api.resource"
        arguments: [ "AppBundle\\Entity\\Post" ]
        tags: [ { name: "api.resource" } ]

    resource.comment:
        parent: "api.resource"
        arguments: [ "AppBundle\\Entity\\Comment" ]
        tags: [ { name: "api.resource" } ]
```

**POST** request
```
{
    "title": "post with comment",
    "comments": [
        "/api/comments/5"
    ]
}
```

**RESPONSE**
```
{
    "@context": "/api/contexts/Post",
    "@id": "/api/posts/8",
    "@type": "Post",
    "title": "post with comment",
    "comments": [
        "/api/comments/5"
    ]
}
```

**GET /api/posts/8**
```
{
    "@context": "/api/contexts/Post",
    "@id": "/api/posts/8",
    "@type": "Post",
    "title": "post with comment",
    "comments": []
}
```

**GET /api/comments/5**
```
{
    "@context": "/api/contexts/Comment",
    "@id": "/api/comments/5",
    "@type": "Comment",
    "title": "comment",
    "post": null
}
```
