### ISSUE TITLE
Search Filter changes POST to resource

### ISSUE THREAD

**Issue by markitosgv** [dunglas/DunglasApiBundle#235]
Hi everyone, 

I've got this config

```yml
    resource.product.search_filter:
        parent:    "api.doctrine.orm.search_filter"
        arguments: [ { "category": "exact" } ]
        
    resource.product:
        parent:    "api.resource"
        arguments: [ AppBundle\Entity\Product ]
        calls:
            -      method:    "initFilters"
                   arguments: [ [ "@resource.product.search_filter" ] ]
        tags:      [ { name: "api.resource" } ]
```

When I configure my service with category filter, then in NelmioAPIDoc POST, PUT operations shows me on sandbox only filter category field and no params appear¿?. However, if i remove resource.product.search_filter then I can do POST action to product, with name, category, description etc...

I'm doing something wrong?
