### ISSUE TITLE
Serialization groups for self-referenced doctrine entity

### ISSUE THREAD

**Issue by blt909** [dunglas/DunglasApiBundle#244]
Hello,

I wonder if it is possible to embed a relation from an entity to the same entity and have different properties shown on GET operation.
I need to get a full user with related users having fewer properties in.

The sample class : 
``` php
/**
 * @ORM\Entity
 * @ORM\Table(name="user")
 */
class User
{
    /**
     * @Groups({"userN", "fewerN",})
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Groups({"userN", "userD"})
     * @Assert\Email
     */
    protected $email;

/**
     * @Groups({"userN","userD", "fewerN"})
     * @ORM\Column(type="string", unique=false, nullable=true)
     */
    private $pseudo;

    /**
     * @Groups({"userN", "fewerN"})
     * @Gedmo\Slug(fields={"pseudo"}, unique=true)
     * @ORM\Column(type="string",length=255, unique=true)
     */
    private $slug;

    /**
     * @Groups({"userN","userD"})
     * @ORM\Column(name="mobile", type="string", nullable=true)
     * @Assert\Type(type="string")
     */
    private $mobile;

    /**
     * @Groups({"userN","userD"})
     * @ORM\Column(name="gender", type="string", nullable=true)
     * @Assert\Type(type="string")
     */
    private $gender;

   /**
     * @ORM\ManyToMany(targetEntity="User", mappedBy="myFriends")
     **/
    private $friendsWithMe;

    
    /**
     * @Groups({"fewerN","userD"})
     * @ORM\ManyToMany(targetEntity="User", inversedBy="friendsWithMe")
     * @ORM\JoinTable(name="friends",
     *      joinColumns={@ORM\JoinColumn(name="friend_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="friendwith_id", referencedColumnName="id")}
     *      )
     **/
    private $myFriends;

}

```

The ressource definition I thinked about : 
```yaml
resource.user:
        parent:         "api.resource"
        arguments:      [ "AppBundle\\Entity\\User" ]
        calls:
            -   method:         "initNormalizationContext"
                arguments:      [ { groups: [ "userN", "fewerN" ] } ]
            -   method:         "initDenormalizationContext"
                arguments:      [ { groups: [ "userD"] } ]
        tags:      [ { name: "api.resource" } ]

```

The wanted result :
```json
{
  "@context": "/api/contexts/User",
  "@id": "/api/users/3",
  "@type": "User",
  "email": "someone@fxlan.com",
  "pseudo": "someone",
  "slug": "someone",
  "mobile": "+33666666666",
  "gender": "male",
  "myFriends": [
    {
      "@id": "/api/users/2",
      "@type": "User",
      "pseudo": "somebody",
      "slug": "somebody",
      "myFriends": []
    }
  ]
}
```

The actual result : 
```json
{
  "@context": "/api/contexts/User",
  "@id": "/api/users/3",
  "@type": "User",
  "email": "someone@fxlan.com",
  "pseudo": "someone",
  "slug": "someone",
  "mobile": "+33666666666",
  "gender": "male",
  "myFriends": [
    {
      "@id": "/api/users/2",
      "@type": "User",
      "email": "somebody@fxlan.com",
      "pseudo": "somebody",
      "slug": "somebody",
      "mobile": "+33666666666",
      "gender": "male",
      "myFriends": []
    }
  ]
}
```
I think there is something I don't understand, but maybe there's a known recipe for that use case.

Thank you.
