### ISSUE TITLE
Custom doctrine Dataprovider not populated with extensions

### ISSUE THREAD

**Issue by soyuka** [dunglas/DunglasApiBundle#298]
The change introduced in https://github.com/dunglas/DunglasApiBundle/commit/62e453ab216b8c228a419070581ebf5549145478 only add method calls on `api.doctrine.orm.data_provider`. Should it not loop through tagged services instead (eg `api.data_provider`)?

Maybe it's the wanted behavior, and currently it has to be implemented in the configuration, for example:

```yaml
    somestuf_data_provider:
        parent: "api.doctrine.orm.data_provider"
        class: 'Acme\SomeBundle\DataProvider\CustomDataProvider'
        calls: 
            - method: 'addCollectionExtension'
              arguments: 
                  - "@api.doctrine.orm.query_extension.pagination"
                  - "@api.doctrine.orm.query_extension.filter"
        tags: [ {name: "api.data_provider", priority: 1 } ]
```
