### ISSUE TITLE
Same entity exposed twice

### ISSUE THREAD

**Issue by 3kynox** [dunglas/DunglasApiBundle#406]
My day to post issues.

I have an entity exposed in services : 

```yml
services:
    resource.ami:
        parent:    "api.resource"
        arguments: [ "ContactBundle\\Entity\\Ami" ]
        calls:
            - method:     "initNormalizationContext"
              arguments:  [{ groups: [ "contacts" ] }]
        tags:      [ { name: "api.resource" } ]
```

can be accessed throught URL .../amis

Now I need to expose again that same entity, but with a different group, where I can open it on a different URL (like .../amis_bis), to expose less properties of this entity.

Is it possible ?

Tks
