### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasApiBundle#81]
The following syntax is considered as a malformed YAML:

```yaml
# app/config/services.yml

services:
    resource.offer.search_filter:
        parent:    "api.doctrine.orm.search_filter"
        arguments: [ {
                        "id": "exact",    # Filters on the id property, allow both numeric values and IRIs
                        "price": "exact", # Extracts all collection elements with the exact given price
                        "name": "partial" # Elements with given text in their name
                   } ]
```

In [Adding Doctrine ORM fitlers](https://github.com/dunglas/DunglasApiBundle/blob/master/Resources/doc/filters.md#adding-doctrine-orm-filters).

A valid one would be:
```yaml
# app/config/services.yml

services:
    resource.offer.search_filter:
        parent:    "api.doctrine.orm.search_filter"
        arguments: [ { id: "exact", price: "exact", name: "partial"  } ]
```

And for very long ones or when we wished to put some comments:

```yaml
# app/config/services.yml

services:
    resource.offer.search_filter:
        parent:    "api.doctrine.orm.search_filter"
        arguments:
            -
                   id:    "exact"      # Filters on the id property, allow both numeric values and IRIs
                   price: "exact"      # Extracts all collection elements with the exact given price
                   name:  "partial"    # Elements with given text in their name
```
