### ISSUE TITLE
Add support for Doctrine ORM filters on embedded relation

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasApiBundle#83]
As seen with @dunglas it would be great to enable filters on embedded relations.

Exemple:

```yaml
services:
    resource.dummy.search_filter:
        parent: api.doctrine.orm.search_filter
        arguments:
            -
                dummyRelation.slug: exact # enable to use search filter on slug property of the target entity
```

And then to use the search filter on it: `?dummyRelation.slug=value`.

The same way for the date and order filter:
* `?dummyRelation.dummyDate[before]=value`
* `?order[dummyRelation.dummyDate]=asc`
