### ISSUE TITLE
Disabling operations causes circular reference

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasApiBundle#92]
I believe there is some issues with the current doc of disabling operations:
* missing `calls` key:

```yaml
resource.product:
    parent:    "api.resource"
    arguments: [ "AppBundle\Entity\Product" ]
    calls: # is missing
        -      [ "initCollectionOperations", [ [ "@resource.product.collection_operation.get" ] ] ]
    tags:      [ { name: "api.resource" } ]
```
* since the `@resource.product` service is registered in `@resource.product.collection_operation.get` and vice-versa it causes a circular reference.

**Comment by dunglas** [comment]
It shouldn't cause circular reference error because of service lazy loading is enabled. Can you upload a not working example?

**Comment by theofidry** [comment]
Using the [api-plateform]() as a base, I changed the service declaration for the `Book` entity into the following:

```yaml
    resource.book.collection_operation.get:
        class:     Dunglas\ApiBundle\Api\Operation\Operation
        factory:   [ @api.operation_factory, createItemOperation ]
        arguments: [ "@resource.book", "GET" ]

    resource.book:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Book" ]
        calls:
            -      [ "initItemOperations", [ [ ] ] ]
            -      [ "initCollectionOperations", [ [ "@resource.book.collection_operation.get" ] ] ]
        tags:      [ { name: "api.resource" } ]
```

The error thrown is:

```
[Symfony\Component\Config\Exception\FileLoaderLoadException]                                                                                                                                                     
  Circular reference detected for service "resource.book.collection_operation.get", path: "resource.book.collection_operation.get" in . (which is being imported from "/path/to/my-api/app/config/routin  
  g.yml").                                                                                                                                                                                                         
                                                                                                                           
  [Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]                                                
  Circular reference detected for service "resource.book.collection_operation.get", path: "resource.book.collection_operation.get".
```
